# Launch instances, runs some tasks

- name: Create a sandbox instance
  hosts: local
  connection: local
  gather_facts: False
  vars:
    keypair: cc-interview-roshan
    instance_type: t2.nano
    security_group: sg-b2bccccb 
    image: ami-87b917e4
    region: ap-southeast-1
  tasks:
    - name: Launch instance
      ec2:
         profile: default
         key_name: "{{ keypair }}"
         group_id: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-a62ca4d1
         assign_public_ip: yes
         instance_tags: '{"Name":"CCInterviewRoshan"}'
         user_data: |
               #!/bin/sh
               sudo apt-get update -y 
               sudo apt-get install python -y
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - set_fact: instance_ip="{{ item.public_ip }}"

- name: Configure instance
  hosts: launched
  become: True
  gather_facts: True

  tasks:
    - name: Installs Nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Upload default index.html for host
      copy: src=/Users/test/Downloads/files/index.html dest=/var/www/html/ mode=0644
   
    - name: print output
      debug: "http://{{ instance_ip }}"

  handlers:
    - name: start Nginx
      service: name=nginx state=started
